### ISSUE TITLE
reweight from variables read from COLVAR

### ISSUE THREAD

**Issue by yuritam648** [kbal/fesbarrier#1]
Hi, I want to use the `REWEIGHT_GEOMFES` functionality in an already completed simulations. I tried to run this command:

```
d1: READ FILE=./COLVAR IGNORE_TIME VALUES=d1
metad: READ FILE=./COLVAR IGNORE_TIME VALUES=metad.rbias
weights1: REWEIGHT_METAD ARG=metad.rbias TEMP=300
hh1: HISTOGRAM ARG=d1 BANDWIDTH=0.05 GRID_BIN=100 GRID_MAX=2.2 GRID_MIN=0.8 LOGWEIGHTS=weights1
weights2: REWEIGHT_GEOMFES ARG=metad.rbias TEMP=300
hh2: HISTOGRAM ARG=d1 BANDWIDTH=0.05 GRID_BIN=100 GRID_MAX=2.2 GRID_MIN=0.8 LOGWEIGHTS=weights2
```

I get an error as below:

```
PLUMED: +++ PLUMED error
PLUMED: +++ at Value.cpp:140, function void PLMD::Value::setGradients()
```

Could you provide some advice how we can use `REWEIGHT_GEOMFES`  for finished simulations? Hope this can be possible in some way to avoid calculating again.

Thank you for providing this nice and useful code and thank you in advance for your help.

**Comment by kbal** [comment]
Some other function needs to request gradients from your CV. You can, for
example, set a dummy wall or something on your CV. I think that should fix
it.

Kristof

**Comment by yuritam648** [comment]
Hi Kristof, thank you. I tried to add dummy wall on my CV but there exists a new error now:

**Command**
`plumed --no-mpi driver --plumed reweight.inp`

**reweight.inp**
```
d1: READ FILE=./COLVAR IGNORE_TIME VALUES=d1
lwall: LOWER_WALLS ARG=d1 AT=0.96 KAPPA=100
metad: READ FILE=./COLVAR IGNORE_TIME VALUES=metad.rbias
weights1: REWEIGHT_METAD ARG=metad.rbias TEMP=300
hh1: HISTOGRAM ARG=d1 BANDWIDTH=0.05 GRID_BIN=100 GRID_MAX=2.2 GRID_MIN=0.8 LOGWEIGHTS=weights1
weights2: REWEIGHT_GEOMFES ARG=d1 TEMP=300
hh2: HISTOGRAM ARG=d1 BANDWIDTH=0.05 GRID_BIN=100 GRID_MAX=2.2 GRID_MIN=0.8 LOGWEIGHTS=weights2
```

**Error**
```
PLUMED: +++ PLUMED error
PLUMED: +++ at Action.cpp:243, function void PLMD::Action::error(const string&) const
PLUMED: +++ message follows +++
PLUMED: ERROR in input to action READ with label d1 : cannot calculate derivatives for colvars that are read in from a file.  If you are postprocessing and these forces do not matter add the flag IGNORE_FORCES to all READ actions
```

Maybe derivatives cannot be calculated in finished calculations. I tried a new way to save derivatives in a new calculation with `DUMPDERIVATIVES` keyword, but I don't find a way to read them in again. Maybe this is a limitations of the plumed software? Thank you.

Yu

**Comment by kbal** [comment]
Ah yes, you need the system coordinates. There's also an option to run
plumed driver on a full MD trajectory (XYZ format or similar). You can't
get gradients if you don't have all positions.

Btw: if the CV is very simple, you can easily calculate this gradient by
hand. (For a distance it'll be constant.)

Kristof

**Comment by yuritam648** [comment]
Thank you Kristof for this advice. `REWEIGHT_GEOMFES  `works well with no error when I use the trajectory file with plumed driver. It was very helpful to talk to you and your code is very useful for us. Thank you for this great work and take care.

Yu
